name: forth
version: 1.7.1.13

language: GHC2021
dependencies:
  - base

library:
  exposed-modules: Forth
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - mtl
    - text

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - forth
      - hspec
